### ISSUE TITLE
Support significant labels

### ISSUE THREAD

**Issue by ShixiangWang** [davidhodge931/ggblanket#153]
Hi,

I just found this useful tool, its very nice to simply the visualization step. I am wondering if it suitable to support the labels for statistical tests. e.g., correlation/p value for correlation dot plot; p value for group comparison in boxplot/violin plot.

Best,

Shixiang

**Comment by davidhodge931** [comment]
Hi, either just add it as a label with your text, or try {ggstatsplot}. Please give the repo a star if you like this package :)
