### ISSUE TITLE
x_zero

### ISSUE THREAD

**Issue by klee8** [davidhodge931/ggblanket#285]
Hey David,

I ran into some issues trying to get x_zero to work. It is in the package help documentation for ggblanket - but I can't find it in the gg_col code (example below). 

Also, setting the plot code keeps throwing an warning message that 'stat' is an unknown parameter when it is passed to ggplot2 (I'm using the current stable release 3.4.1)

![image](https://user-images.githubusercontent.com/9483236/228963269-57780395-4099-4d3c-8273-c67c37b910a0.png)

Cheers,

Kate

plot <- palmerpenguins::penguins %>%
  group_by(species) %>%
  summarise(average_bill = mean(bill_length_mm, na.rm = TRUE)) %>%
  mutate(species = forcats::fct_reorder(species, average_bill, .desc = TRUE)) %>%
gg_col(
  x = average_bill,
  y = species,
  stat = "identity",
  width = 0.75,
  x_zero = FALSE,
  title = "Penguin species average bill length (mm)", 
  y_title = "", 
  x_title = "bill length (mm)",
  y_labels = stringr::str_to_sentence,
  position = "dodge"
)
plot

**Comment by davidhodge931** [comment]
Hey Kate, 

Hope you're well. 

geom_col doesn't have the stat argument in it, so a message will come up with this if you add it in. I just left it in gg_col, as I wanted all the functions to be the same.

There are no *_zero arguments in ggblanket. Just *_include or *_limits, depending on what you are trying to do.

For example, making bars that have a min limit of 20...

```
library(tidyverse)
library(ggblanket)
library(palmerpenguins)

penguins %>%
  group_by(species) %>%
  summarise(average_bill = mean(bill_length_mm, na.rm = TRUE)) %>%
  mutate(species = forcats::fct_reorder(species, average_bill, .desc = TRUE)) %>%
  gg_col(
    x = average_bill,
    y = species,
    width = 0.75,
    x_limits = c(20, max(pretty(.$average_bill, n = 6)))
  )
```

Are you still based in Wellington? Be cool to catch up some time

**Comment by davidhodge931** [comment]
Also, `x_zero` should not be in the help for ggblanket, as it is not a ggblanket:::gg_col argument??

**Comment by klee8** [comment]
Hi David,

Apologies, I was sick last week and am just catching up with emails now.
I'm actually based in Christchurch now. But I'll be around on the morning
of the 30th May if you're keen for lunch/coffee?

Cheers,

Kate

**Comment by davidhodge931** [comment]
Oh yeah, that'd be great. I normally go to a yoga class 12-1 in town. I could meet you before or after? Like 10:30 coffee somewhere, or 130 lunch/coffee somewhere? Do you use whatsApp? Message me on that if it's easier

**Comment by klee8** [comment]
Either of those suit me fine :) Lunch might give us a bit more time?

Kate
