### ISSUE TITLE
contour: remove contour = TRUE code if ggplot2 fixes

### ISSUE THREAD

**Issue by davidhodge931** [davidhodge931/ggblanket#621]

**Comment by davidhodge931** [comment]
ggplot2 #5571

**Comment by rkportal** [comment]
I'm not sure if it's the same issue, but all the geoms I tried pop the warning "Ignoring unknown parameters: `contour`" every single use. see here for gg_line:

``` r
library(palmerpenguins)
library(tidyverse)
library(ggblanket)

penguins |> ggblanket::gg_line(x = bill_length_mm, y = body_mass_g)
#> Warning in gg_blanket(data = data, geom = "line", stat = stat, position = position, : Ignoring unknown parameters: `contour`
#> Ignoring unknown parameters: `contour`
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_line()`).
```

![](https://i.imgur.com/GmuNfR1.png)

<sup>Created on 2024-04-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
 
it's pretty much the only reason I'm not moving all my graphs to ggblanket

**Comment by davidhodge931** [comment]
I'll update this next version to remove

**Comment by davidhodge931** [comment]
Download from github, if you want to get this now @rkportal . Otherwise v7.1.0 on CRAN in a few weeks

**Comment by rkportal** [comment]
I reinstalled from github and the warning is gone, thanks!

**Comment by davidhodge931** [comment]
Just got rid of the other annoying duplicate messages/warnings that were happening in gg_histogram etc
