### ISSUE TITLE
dependencies: what packages to include in Suggests

### ISSUE THREAD

**Issue by davidhodge931** [davidhodge931/ggblanket#639]
I'm not sure what Suggests packages I should have. I've added these fairly haphazardly.

knitr seems to be required -as the Check fails without it. I added palmerpenguins in heaps of the examples. patchwork is super useful. So I added it.. Can't remember why I have stats in it. The others I thought were crucial packages for quantile, hex, contour and sf plots.

I already have ggplot2 as an Import, so maybe that covers off some of the others.. 

![image](https://github.com/davidhodge931/ggblanket/assets/55065152/cb51374a-fbfb-4b18-ac34-413e061e9409)

**Comment by davidhodge931** [comment]
@olivroy if you have any thoughts here, they would be much appreciated :)

**Comment by olivroy** [comment]
Well, stats in not needed there.

Any package you use in examples should be in Suggests.

If you only use a package in an [article](https://r-pkgs.org/vignettes.html#sec-vignettes-article), you only need it in `Config/Needs/website`.

stats is probably not necessary.

hexbin is required if some examples use `geom_hex()`. isoband is probably not required as it is imported by ggplot2.

For tibble, if you use only `tibble()`, or `as_tibble()`, or a function that [dplyr reexports](https://dplyr.tidyverse.org/reference/reexports.html), you can probably use `dplyr::tibble()`, `dplyr::as_tibble()`, etc.

**Comment by davidhodge931** [comment]
Thanks @olivroy I've dropped stats and patchwork as a result of your comments
