### ISSUE TITLE
autocomplete: theme argument loses first argument in Rstudio auto-complete

### ISSUE THREAD

**Issue by davidhodge931** [davidhodge931/ggblanket#661]
Unable to see the base_size argument in the example below

Seems to be related to this
https://github.com/rstudio/rstudio/issues/13611

Maybe there is a hack that could make it work? Or maybe just need to wait for Rstudio to fix?
<img width="329" alt="image" src="https://github.com/davidhodge931/ggblanket/assets/55065152/4981b70a-0ea5-44f1-94b0-1079b9dc4cf0">

**Comment by olivroy** [comment]
Pretty sure waiting for RStudio fix is the only way here (or trying to fix the RStudio issue in their code!). (Upvoting and commenting on issues on the RStudio repo is a good way to let them know it is important
